//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// KIBOSYSTEM.rc で使用
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_KIBOSYSTEMTYPE              130
#define IDD_INPUT                       131
#define ID_WINDOW_MANAGER               131
#define IDD_SELECT                      132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDD_SECONDDISPLAY               200
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDM_CAMERAFILE_SAVE             401
#define IDM_800                         501
#define IDM_1024                        502
#define IDM_2048                        503
#define IDM_2592                        504
#define IDM_STREATCH                    505
#define IDC_EDIT                        1000
#define IDC_SPIN                        1001
#define IDM_DUMY1                       32771
#define ID_BUTTON32771                  32771
#define ID_RIGHT                        32779
#define ID_LEFT                         32780
#define ID_UP                           32781
#define ID_DOWN                         32782
#define ID_PAGEUP                       32784
#define ID_PAGEDOWN                     32785
#define ID_HOME                         32800
#define ID_SPACE                        32801
#define ID_PLUS                         32804
#define ID_MINUS                        32805
#define ID_A                            32811
#define ID_B                            32812
#define ID_C                            32813
#define ID_D                            32814
#define ID_E                            32815
#define ID_F                            32816
#define ID_G                            32817
#define ID_H                            32818
#define ID_I                            32819
#define ID_J                            32820
#define ID_K                            32821
#define ID_L                            32822
#define ID_M                            32823
#define ID_N                            32824
#define ID_O                            32825
#define ID_P                            32826
#define ID_Q                            32827
#define ID_R                            32828
#define ID_S                            32829
#define ID_T                            32830
#define ID_U                            32831
#define ID_V                            32832
#define ID_W                            32833
#define ID_X                            32834
#define ID_Y                            32835
#define ID_Z                            32836
#define ID_F1                           32841
#define ID_F2                           32842
#define ID_F3                           32843
#define ID_F4                           32844
#define ID_F5                           32845
#define ID_F6                           32846
#define ID_F7                           32847
#define ID_F8                           32848
#define ID_F9                           32849
#define ID_F10                          32850
#define ID_F11                          32851
#define ID_F12                          32852

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        310
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
